# Generated by Django 3.0.5 on 2021-11-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pplxtramites',
            name='fecha_envio_tramite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pplxtramites',
            name='fecha_peticion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo_hv',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
